[package]
name = "livekit_integration"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
jsonwebtoken.workspace = true
serde.workspace = true
shared = { path = "../shared" }

[dev-dependencies]
serde_json.workspace = true
